[build]
  base    = "frontend"
  publish = "dist"
  command = "npm run build"

[dev]
  command = "npm run dev"
  port = "${FRONTEND_PORT}"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
