# Common configuration for all services
x-common-env: &common-env
  env_file: ../.env

services:
  backend:
    <<: *common-env
    build:
      context: ..
      dockerfile: docker/backend/Dockerfile.dev
      target: dev
    ports:
      - "${BACKEND_PORT}:8000"
    volumes:
      - ../backend:/app
      - ../design-assets:/app/design-assets
      - backend_venv:/app/.venv
    environment:
      - DATABASE_URL=postgresql://aris:aris@postgres:5432/${DB_NAME}
      - TEST_DB_URL=postgresql+asyncpg://aris:aris@postgres:5432/${TEST_DB_NAME}
      - ALEMBIC_DB_URL_LOCAL=postgresql://aris:aris@postgres:5432/${TEST_DB_NAME}
      - DB_URL_LOCAL=postgresql+asyncpg://aris:aris@postgres:5432/${TEST_DB_NAME}
      - DB_URL_PROD=postgresql+asyncpg://aris:aris@postgres:5432/${TEST_DB_NAME}
      - ALEMBIC_DB_URL_PROD=postgresql://aris:aris@postgres:5432/${TEST_DB_NAME}
      - ENV=${ENV:-LOCAL}
      - CONTAINER_ENV=true
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - COPILOT_PROVIDER=${COPILOT_PROVIDER}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - TEST_USER_EMAIL=${TEST_USER_EMAIL}
      - TEST_USER_PASSWORD=${TEST_USER_PASSWORD}
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    
  frontend:
    <<: *common-env
    build:
      context: ..
      dockerfile: docker/frontend/Dockerfile.dev
      target: dev
    ports:
      - "${FRONTEND_PORT}:5173"
    volumes:
      - ../frontend:/app
      - frontend_node_modules:/app/node_modules
    environment:
      - VITE_API_BASE_URL=http://localhost:${BACKEND_PORT}
    command: npm run dev -- --host 0.0.0.0
    
  storybook:
    <<: *common-env
    build:
      context: ..
      dockerfile: docker/frontend/Dockerfile.dev
      target: dev
    ports:
      - "${STORYBOOK_PORT}:${STORYBOOK_PORT}"
    volumes:
      - ../frontend:/app
      - frontend_node_modules:/app/node_modules
    environment:
      - VITE_API_BASE_URL=http://backend:8000
    command: npm run storybook -- --host 0.0.0.0 --no-open
    
  site:
    <<: *common-env
    build:
      context: ..
      dockerfile: docker/site/Dockerfile.dev
      target: dev
    ports:
      - "${SITE_PORT}:3000"
    volumes:
      - ../site:/app
      - site_node_modules:/app/node_modules
    environment:
      - FRONTEND_URL=http://localhost:${FRONTEND_PORT}
      - NUXT_BACKEND_URL=http://localhost:${BACKEND_PORT}
    command: npm run dev
    
  postgres:
    <<: *common-env
    image: postgres:16
    ports:
      - "${DB_PORT}:5432"
    environment:
      - POSTGRES_USER=aris
      - POSTGRES_PASSWORD=aris
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/init_test_db.sql:/docker-entrypoint-initdb.d/init_test_db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U aris"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  backend_venv:
  frontend_node_modules:
  site_node_modules:
  postgres_data: