"""Add email tracking fields to signup table

Revision ID: 14808df09e7d
Revises: 9fe3d6fca545
Create Date: 2025-06-26 18:08:56.649315

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '14808df09e7d'
down_revision: Union[str, None] = '9fe3d6fca545'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('signups', sa.Column('email_sent', sa.Boolean(), nullable=False))
    op.add_column('signups', sa.Column('email_sent_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('signups', 'email_sent_at')
    op.drop_column('signups', 'email_sent')
    # ### end Alembic commands ###
