"""add signup table

Revision ID: 369a8fbaa6f0
Revises: 358cb873fb7e
Create Date: 2025-06-23 14:39:27.220334

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '369a8fbaa6f0'
down_revision: Union[str, None] = '358cb873fb7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('signups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('institution', sa.String(), nullable=True),
    sa.Column('research_area', sa.String(), nullable=True),
    sa.Column('interest_level', sa.Enum('EXPLORING', 'PLANNING', 'READY', 'MIGRATING', name='interestlevel'), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'UNSUBSCRIBED', 'CONVERTED', name='signupstatus'), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('consent_given', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signups_email'), 'signups', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_signups_email'), table_name='signups')
    op.drop_table('signups')
    # ### end Alembic commands ###
