"""Add version and prev_version_id fields to File model

Revision ID: 59878b55c0bc
Revises: fcc9ed287b43
Create Date: 2025-07-16 15:39:12.427042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59878b55c0bc'
down_revision: Union[str, None] = 'fcc9ed287b43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('version', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('files', sa.Column('prev_version_id', sa.Integer(), nullable=True))
    op.create_index('ix_files_prev_version_id', 'files', ['prev_version_id'], unique=False)
    op.create_index('ix_files_version', 'files', ['version'], unique=False)
    op.create_foreign_key(None, 'files', 'files', ['prev_version_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'files', type_='foreignkey')
    op.drop_index('ix_files_version', table_name='files')
    op.drop_index('ix_files_prev_version_id', table_name='files')
    op.drop_column('files', 'prev_version_id')
    op.drop_column('files', 'version')
    # ### end Alembic commands ###
