"""add user settings table

Revision ID: 8927a9754c0b
Revises: 14808df09e7d
Create Date: 2025-06-30 16:30:54.006006

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '8927a9754c0b'
down_revision: Union[str, None] = '14808df09e7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('auto_save_interval', sa.Integer(), nullable=False),
    sa.Column('focus_mode_auto_hide', sa.Boolean(), nullable=False),
    sa.Column('sidebar_auto_collapse', sa.Boolean(), nullable=False),
    sa.Column('drawer_default_annotations', sa.Boolean(), nullable=False),
    sa.Column('drawer_default_margins', sa.Boolean(), nullable=False),
    sa.Column('drawer_default_settings', sa.Boolean(), nullable=False),
    sa.Column('sound_notifications', sa.Boolean(), nullable=False),
    sa.Column('auto_compile_delay', sa.Integer(), nullable=False),
    sa.Column('mobile_menu_behavior', sa.String(), nullable=False),
    sa.Column('allow_anonymous_feedback', sa.Boolean(), nullable=False),
    sa.Column('email_digest_frequency', sa.String(), nullable=False),
    sa.Column('notification_preference', sa.String(), nullable=False),
    sa.Column('notification_mentions', sa.Boolean(), nullable=False),
    sa.Column('notification_comments', sa.Boolean(), nullable=False),
    sa.Column('notification_shares', sa.Boolean(), nullable=False),
    sa.Column('notification_system', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='uq_user_settings_per_user')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_settings')
    # ### end Alembic commands ###
