"""Add unsubscribe_token and unsubscribed_at to signups table

Revision ID: 9fe3d6fca545
Revises: 369a8fbaa6f0
Create Date: 2025-06-23 20:10:29.334610

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '9fe3d6fca545'
down_revision: Union[str, None] = '369a8fbaa6f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('signups', sa.Column('unsubscribe_token', sa.String(), nullable=False))
    op.add_column('signups', sa.Column('unsubscribed_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_signups_unsubscribe_token'), 'signups', ['unsubscribe_token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_signups_unsubscribe_token'), table_name='signups')
    op.drop_column('signups', 'unsubscribed_at')
    op.drop_column('signups', 'unsubscribe_token')
    # ### end Alembic commands ###
