"""Add publication status fields to File model

Revision ID: fcc9ed287b43
Revises: f16cfc973685
Create Date: 2025-07-16 14:05:43.947119

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'fcc9ed287b43'
down_revision: Union[str, None] = 'f16cfc973685'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('published_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('files', sa.Column('public_uuid', sa.String(length=6), nullable=True))
    op.add_column('files', sa.Column('permalink_slug', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'files', ['permalink_slug'])
    op.create_unique_constraint(None, 'files', ['public_uuid'])
    
    # Create performance indexes
    op.create_index('ix_files_published_at', 'files', ['published_at'])
    op.create_index('ix_files_public_uuid', 'files', ['public_uuid'], unique=True)
    op.create_index('ix_files_permalink_slug', 'files', ['permalink_slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop performance indexes first
    op.drop_index('ix_files_permalink_slug', 'files')
    op.drop_index('ix_files_public_uuid', 'files')
    op.drop_index('ix_files_published_at', 'files')
    
    op.drop_constraint(None, 'files', type_='unique')
    op.drop_constraint(None, 'files', type_='unique')
    op.drop_column('files', 'permalink_slug')
    op.drop_column('files', 'public_uuid')
    op.drop_column('files', 'published_at')
    # ### end Alembic commands ###
