name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      backend: ${{ steps.changes.outputs.backend }}
      frontend: ${{ steps.changes.outputs.frontend }}
      site: ${{ steps.changes.outputs.site }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            backend:
              - 'backend/**'
            frontend:
              - 'frontend/**'
            site:
              - 'site/**'

  # PHASE 1: Unit Tests and Linting (Parallel)
  backend-test:
    runs-on: ubuntu-latest
    needs: changes
    if: ${{ always() }}
    env:
      ENV: CI
      TEST_USER_PASSWORD: ${{ secrets.TEST_USER_PASSWORD }}

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_aris
          POSTGRES_HOST_AUTH_METHOD: trust
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    defaults:
      run:
        working-directory: backend

    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        version: "latest"

    - name: Create virtual environment
      run: uv venv

    - name: Set up Python
      run: uv python install 3.13

    - name: Sync dependencies
      run: uv sync --group test

    - name: Run linting (ruff)
      run: uv run ruff check

    - name: Wait for PostgreSQL to be ready
      run: |
        until pg_isready -h localhost -p 5432 -U postgres; do
          echo "Waiting for PostgreSQL..."
          sleep 2
        done
        echo "PostgreSQL is ready!"

    - name: Test PostgreSQL connection
      run: |
        echo "Testing PostgreSQL connection..."
        psql -h localhost -p 5432 -U postgres -d test_aris -c "SELECT version();"
      env:
        PGPASSWORD: postgres

    - name: Debug env & .env.ci file
      run: |
        echo "ENV=$ENV"
        echo "TEST_USER_PASSWORD is set: $([ -n "$TEST_USER_PASSWORD" ] && echo "yes" || echo "no")"
        echo "GITHUB_ACTIONS=$GITHUB_ACTIONS"
        ls -l .env.ci
        cat .env.ci

    - name: Run tests
      run: uv run pytest -n8 --cov=aris --cov-report=xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v5
      with:
        files: ./backend/coverage.xml
        flags: backend
        token: ${{ secrets.CODECOV_TOKEN }}

  frontend-test:
    runs-on: ubuntu-latest
    needs: changes
    if: ${{ always() }}

    defaults:
      run:
        working-directory: frontend

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '23'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json

    - name: Install dependencies
      run: npm ci

    - name: Check for missing packages
      run: npm ls --depth=0

    - name: Run linting
      run: npm run lint

    - name: Run tests
      run: npm run test:coverage

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v5
      with:
        files: ./frontend/coverage/lcov.info
        flags: frontend
        token: ${{ secrets.CODECOV_TOKEN }}

  site-test:
    runs-on: ubuntu-latest
    needs: changes
    if: ${{ always() }}

    defaults:
      run:
        working-directory: site

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '23'
        cache: 'npm'
        cache-dependency-path: site/package-lock.json

    - name: Install dependencies
      run: npm ci

    - name: Check for missing packages
      run: npm ls --depth=0

    - name: Run linting
      run: npm run lint

    - name: Run unit tests
      run: npm run test:run

  # PHASE 2: E2E Tests (Depends on Phase 1)
  site-e2e:
    runs-on: ubuntu-latest
    needs: [changes, site-test]
    if: ${{ always() && (needs.site-test.result == 'success' || needs.site-test.result == 'skipped') }}

    defaults:
      run:
        working-directory: site

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '23'
        cache: 'npm'
        cache-dependency-path: site/package-lock.json

    - name: Install dependencies
      run: npm ci

    - name: Install Playwright browsers
      run: npx playwright install --with-deps

    - name: Run E2E tests (excluding demo integration)
      run: npm run test:e2e:all -- --grep-invert "demo"

  frontend-e2e-auth:
    runs-on: ubuntu-latest
    needs: [changes, backend-test, frontend-test]
    if: ${{ always() && (needs.backend-test.result == 'success' || needs.backend-test.result == 'skipped') && (needs.frontend-test.result == 'success' || needs.frontend-test.result == 'skipped') }}
    env:
      ENV: CI
      TEST_USER_PASSWORD: ${{ secrets.TEST_USER_PASSWORD }}
      # Only this job has real auth - others use DISABLE_AUTH=true

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_aris
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v4

    # Backend setup
    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        version: "latest"

    - name: Set up Python
      run: uv python install 3.13

    - name: Setup backend
      working-directory: backend
      run: |
        uv venv
        uv sync --all-groups
        uv pip install -e .

    - name: Setup database and test data
      working-directory: backend
      run: |
        echo "ENV=$ENV"
        echo "Current working directory: $(pwd)"
        echo "Contents of .env.ci:"
        cat .env.ci
        uv run alembic upgrade head
        uv run python scripts/reset_test_user.py

    # Frontend setup
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '23'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json

    - name: Install frontend dependencies
      working-directory: frontend
      run: npm ci

    - name: Install Playwright browsers
      working-directory: frontend
      run: npx playwright install --with-deps

    # Start servers
    - name: Start backend server
      working-directory: backend
      run: uv run uvicorn main:app --host 0.0.0.0 --port 8000 &

    - name: Start frontend server
      working-directory: frontend
      run: npm run dev -- --host 0.0.0.0 --port 5173 &
      env:
        VITE_DEV_LOGIN_PASSWORD: ${{ secrets.TEST_USER_PASSWORD }}

    - name: Wait for servers to be ready
      run: |
        timeout 60 bash -c 'until curl -f http://localhost:8000/health; do sleep 2; done'
        timeout 60 bash -c 'until curl -f http://localhost:5173; do sleep 2; done'

    - name: Run Frontend E2E tests (Auth)
      working-directory: frontend
      run: npm run test:e2e -- --grep "(login|auth|registration|account)"
      env:
        VITE_DEV_LOGIN_PASSWORD: ${{ secrets.TEST_USER_PASSWORD }}

  frontend-e2e-demo:
    runs-on: ubuntu-latest
    needs: [changes, backend-test, frontend-test, site-test]
    if: ${{ always() && (needs.backend-test.result == 'success' || needs.backend-test.result == 'skipped') && (needs.frontend-test.result == 'success' || needs.frontend-test.result == 'skipped') && (needs.site-test.result == 'success' || needs.site-test.result == 'skipped') }}
    env:
      ENV: CI
      TEST_USER_PASSWORD: ${{ secrets.TEST_USER_PASSWORD }}
      DISABLE_AUTH: true

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_aris
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v4

    # Backend setup
    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        version: "latest"

    - name: Set up Python
      run: uv python install 3.13

    - name: Setup backend
      working-directory: backend
      run: |
        uv venv
        uv sync --all-groups
        uv pip install -e .

    - name: Setup database and test data
      working-directory: backend
      run: |
        echo "ENV=$ENV"
        echo "Current working directory: $(pwd)"
        echo "Contents of .env.ci:"
        cat .env.ci
        uv run alembic upgrade head
        uv run python scripts/reset_test_user.py

    # Frontend setup
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '23'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json

    - name: Install frontend dependencies
      working-directory: frontend
      run: npm ci

    - name: Install Playwright browsers
      working-directory: frontend
      run: npx playwright install --with-deps

    # Start servers
    - name: Start backend server
      working-directory: backend
      run: uv run uvicorn main:app --host 0.0.0.0 --port 8000 &

    - name: Start frontend server
      working-directory: frontend
      run: npm run dev -- --host 0.0.0.0 --port 5173 &
      env:
        VITE_DEV_LOGIN_PASSWORD: ${{ secrets.TEST_USER_PASSWORD }}

    - name: Wait for servers to be ready
      run: |
        timeout 60 bash -c 'until curl -f http://localhost:8000/health; do sleep 2; done'
        timeout 60 bash -c 'until curl -f http://localhost:5173; do sleep 2; done'

    - name: Run Frontend E2E tests (Demo)
      working-directory: frontend
      run: npm run test:e2e -- --grep "demo"
      env:
        VITE_DEV_LOGIN_PASSWORD: ${{ secrets.TEST_USER_PASSWORD }}

  frontend-e2e-home:
    runs-on: ubuntu-latest
    needs: [changes, backend-test, frontend-test]
    if: ${{ always() && (needs.backend-test.result == 'success' || needs.backend-test.result == 'skipped') && (needs.frontend-test.result == 'success' || needs.frontend-test.result == 'skipped') }}
    env:
      ENV: CI
      TEST_USER_PASSWORD: ${{ secrets.TEST_USER_PASSWORD }}
      DISABLE_AUTH: true

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_aris
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v4

    # Backend setup
    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        version: "latest"

    - name: Set up Python
      run: uv python install 3.13

    - name: Setup backend
      working-directory: backend
      run: |
        uv venv
        uv sync --all-groups
        uv pip install -e .

    - name: Setup database and test data
      working-directory: backend
      run: |
        echo "ENV=$ENV"
        echo "Current working directory: $(pwd)"
        echo "Contents of .env.ci:"
        cat .env.ci
        uv run alembic upgrade head
        uv run python scripts/reset_test_user.py

    # Frontend setup
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '23'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json

    - name: Install frontend dependencies
      working-directory: frontend
      run: npm ci

    - name: Install Playwright browsers
      working-directory: frontend
      run: npx playwright install --with-deps

    # Start servers
    - name: Start backend server
      working-directory: backend
      run: uv run uvicorn main:app --host 0.0.0.0 --port 8000 &

    - name: Start frontend server
      working-directory: frontend
      run: npm run dev -- --host 0.0.0.0 --port 5173 &
      env:
        VITE_DEV_LOGIN_PASSWORD: ${{ secrets.TEST_USER_PASSWORD }}

    - name: Wait for servers to be ready
      run: |
        timeout 60 bash -c 'until curl -f http://localhost:8000/health; do sleep 2; done'
        timeout 60 bash -c 'until curl -f http://localhost:5173; do sleep 2; done'

    - name: Run Frontend E2E tests (Home/Files)
      working-directory: frontend
      run: npm run test:e2e -- --grep "(home|file)"
      env:
        VITE_DEV_LOGIN_PASSWORD: ${{ secrets.TEST_USER_PASSWORD }}

  frontend-e2e-workspace:
    runs-on: ubuntu-latest
    needs: [changes, backend-test, frontend-test]
    if: ${{ always() && (needs.backend-test.result == 'success' || needs.backend-test.result == 'skipped') && (needs.frontend-test.result == 'success' || needs.frontend-test.result == 'skipped') }}
    env:
      ENV: CI
      TEST_USER_PASSWORD: ${{ secrets.TEST_USER_PASSWORD }}
      DISABLE_AUTH: true

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_aris
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v4

    # Backend setup
    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        version: "latest"

    - name: Set up Python
      run: uv python install 3.13

    - name: Setup backend
      working-directory: backend
      run: |
        uv venv
        uv sync --all-groups
        uv pip install -e .

    - name: Setup database and test data
      working-directory: backend
      run: |
        echo "ENV=$ENV"
        echo "Current working directory: $(pwd)"
        echo "Contents of .env.ci:"
        cat .env.ci
        uv run alembic upgrade head
        uv run python scripts/reset_test_user.py

    # Frontend setup
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '23'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json

    - name: Install frontend dependencies
      working-directory: frontend
      run: npm ci

    - name: Install Playwright browsers
      working-directory: frontend
      run: npx playwright install --with-deps

    # Start servers
    - name: Start backend server
      working-directory: backend
      run: uv run uvicorn main:app --host 0.0.0.0 --port 8000 &

    - name: Start frontend server
      working-directory: frontend
      run: npm run dev -- --host 0.0.0.0 --port 5173 &
      env:
        VITE_DEV_LOGIN_PASSWORD: ${{ secrets.TEST_USER_PASSWORD }}

    - name: Wait for servers to be ready
      run: |
        timeout 60 bash -c 'until curl -f http://localhost:8000/health; do sleep 2; done'
        timeout 60 bash -c 'until curl -f http://localhost:5173; do sleep 2; done'

    - name: Run Frontend E2E tests (Workspace)
      working-directory: frontend
      run: npm run test:e2e -- --grep "(workspace|sidebar|drawer|focus)"
      env:
        VITE_DEV_LOGIN_PASSWORD: ${{ secrets.TEST_USER_PASSWORD }}

  frontend-e2e-other:
    runs-on: ubuntu-latest
    needs: [changes, backend-test, frontend-test]
    if: ${{ always() && (needs.backend-test.result == 'success' || needs.backend-test.result == 'skipped') && (needs.frontend-test.result == 'success' || needs.frontend-test.result == 'skipped') }}
    env:
      ENV: CI
      TEST_USER_PASSWORD: ${{ secrets.TEST_USER_PASSWORD }}
      DISABLE_AUTH: true

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_aris
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v4

    # Backend setup
    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        version: "latest"

    - name: Set up Python
      run: uv python install 3.13

    - name: Setup backend
      working-directory: backend
      run: |
        uv venv
        uv sync --all-groups
        uv pip install -e .

    - name: Setup database and test data
      working-directory: backend
      run: |
        echo "ENV=$ENV"
        echo "Current working directory: $(pwd)"
        echo "Contents of .env.ci:"
        cat .env.ci
        uv run alembic upgrade head
        uv run python scripts/reset_test_user.py

    # Frontend setup
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '23'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json

    - name: Install frontend dependencies
      working-directory: frontend
      run: npm ci

    - name: Install Playwright browsers
      working-directory: frontend
      run: npx playwright install --with-deps

    # Start servers
    - name: Start backend server
      working-directory: backend
      run: uv run uvicorn main:app --host 0.0.0.0 --port 8000 &

    - name: Start frontend server
      working-directory: frontend
      run: npm run dev -- --host 0.0.0.0 --port 5173 &
      env:
        VITE_DEV_LOGIN_PASSWORD: ${{ secrets.TEST_USER_PASSWORD }}

    - name: Wait for servers to be ready
      run: |
        timeout 60 bash -c 'until curl -f http://localhost:8000/health; do sleep 2; done'
        timeout 60 bash -c 'until curl -f http://localhost:5173; do sleep 2; done'

    - name: Run Frontend E2E tests (Other)
      working-directory: frontend
      run: npm run test:e2e -- --grep-invert "(login|auth|registration|account|demo|home|file|workspace|sidebar|drawer|focus)"
      env:
        VITE_DEV_LOGIN_PASSWORD: ${{ secrets.TEST_USER_PASSWORD }}